######################################################################
# Automatically generated by qmake (1.07a) Thu Jan 1 06:28:52 1970
######################################################################

TEMPLATE = app
INCLUDEPATH += .

TARGET = 8Q

# Input
HEADERS += form8q.h
SOURCES += form8q.cpp main.cpp

OBJECTS_DIR = .obj
MOC_DIR = .moc
