    DEVICE ZXSPECTRUM48
    
    ORG	 #4000
;    incbin "8queenscr.bin"

    
    ORG  $8000
    
START:	CALL	CALC_AND_DRAW+2	; CALL CALC_AND_DRAW from 8queen.bin see below, 2 bytes for queen's results addr
	CALL	BOARD
	LD	A,1
	CALL	DRAW_MARKER
	CALL	QUEENS
	EI
	; Keyboard Input
WAIT:	CALL	KEYBOARD_READ
	CP	2	; Q
	JR	NZ,WAIT1
	LD	A,(QUEENS_ROW)
	CP	0	; CHECK BOTTOM BOUNDARY NUMBER
	JR	Z,WAIT_END
	CALL	ERASE_SET
	LD	HL,QUEENS_ROW
	DEC	(HL)
	CALL	DRAW_SET
	JR	WAIT_END
WAIT1:	CP	3	; A
	JR	NZ,WAIT2
	LD	A,(QUEENS_ROW)
	CP	22	; 1 CHESS TOP BOUNDARY NUMBER
	JR	Z,WAIT_END
	CALL	ERASE_SET
	LD	HL,QUEENS_ROW
	INC	(HL)
	CALL	DRAW_SET
	JR	WAIT_END
WAIT2:	CP	4	; P
	JR	NZ,WAIT3
	LD	A,(QUEENS_COL)
	CP	3
	JR	Z,WAIT_END
	CALL	ERASE_SET
	LD	HL,QUEENS_COL
	INC	(HL)
	CALL	DRAW_SET
	JR	WAIT_END
WAIT3:	CP	5	; O
	JR	NZ,WAIT4
	LD	A,(QUEENS_COL)
	CP	0
	JR	Z,WAIT_END
	CALL	ERASE_SET
	LD	HL,QUEENS_COL
	DEC	(HL)
	CALL	DRAW_SET
	JR	WAIT_END
WAIT4:	CP	1	; SPACE
	JR	NZ,WAIT_END
	CALL	QUEENS ;XOR OLD SET
WAIT_END:	LD	B,4
WAIT_CYCLE:	HALT
		DJNZ WAIT_CYCLE
	JR	WAIT
	RET

BOARD:	LD	HL,#5888	;DRAW CHESS BOARD BY COLOR ATTRIBUTES
	LD	C,16
ROW:	LD	B,16
	PUSH	HL
COL:	
	LD	A,C
	DEC	A
	SRA	A
	AND	1
	LD	E,A
	LD	A,B
	DEC	A
	SRA	A
	XOR	E
	AND	1
	JR	Z,EMPTY1
	LD	A,%01011000	; "Black" square
	JR	FILL1
EMPTY1:	LD	A,%00111000	; "White" square
FILL1:	LD	(HL),A	
	INC	HL
	DJNZ	COL
	POP	HL
	LD	DE,32
	ADD	HL,DE
	DEC	C
	JR	NZ,ROW
	RET

ERASE_SET:
	LD	A,0
	CALL	DRAW_MARKER
	CALL	QUEENS	;XOR OLD SET OF QUEENS
	RET

DRAW_SET:
	LD	A,1
	CALL	DRAW_MARKER
	CALL	QUEENS  ;DRAW NEW SET
	RET

DRAW_MARKER:	; A - MODE COLOR=1/RESTORE=0
	PUSH	AF
	LD	DE,#5820
	LD	A,(QUEENS_ROW)
	LD	H,0
	LD	L,A
	ADD	HL,HL
	ADD	HL,HL
	LD	A,(QUEENS_COL)
	LD	B,0
	LD	C,A
	ADD	HL,BC
	ADD	HL,HL 
	ADD	HL,HL 
	ADD	HL,HL	; HL=8*HL
	ADD	HL,DE	; HL - address begin of marker
	POP	AF
	LD	B,8
	CP	1
	JR	Z,DRAW_SAVE
	JR	DRAW_RESTORE
DRAW_SAVE:	LD	DE,MARKER_BACK
	PUSH	HL
DRAW_S1:	
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	DRAW_S1
	POP	HL
	LD	B,8
	LD	A,(MARKER_COLOR)
DRAW_C1:	LD	(HL),A
	INC	HL
	DJNZ	DRAW_C1
	RET
DRAW_RESTORE:
	LD	DE,MARKER_BACK
DRAW_R1:
	LD	A,(DE)
	LD	(HL),A
	INC	HL
	INC	DE	
	DJNZ	DRAW_R1
	RET
	
	
QUEENS:	
	LD	DE,(CALC_AND_DRAW)	; DRAW ALL QUEENS IN SET
	LD	A,(QUEENS_ROW)
	LD	H,0
	LD	L,A
	ADD	HL,HL
	ADD	HL,HL
	LD	A,(QUEENS_COL)
	LD	B,0
	LD	C,A
	ADD	HL,BC
	ADD	HL,HL 
	ADD	HL,HL ; HL=4*HL
	ADD	HL,DE ; HL - address begin of current queens's set
	LD	IX,HL
	LD	C,0
	LD	B,8
QUEEN:	LD	A,(IX)
	BIT	0,B
	JR	NZ,LDIGIT
	SRA	A
	SRA	A
	SRA	A
	SRA	A
	DEC	IX 	; IT HAS TO BE USED SECOND TIME FOR LOW DECIMAL DIGIT
LDIGIT:		
	AND	#0F
	DEC	A	; NUMBER [1-8] -> [0-7]
	LD	D,A
	LD	A,7
	SUB	D
	ADD	A,2
	LD	D,A
	SRA	A
	SRA	A
	LD	E,A	; NUMBER OF THIRD SECTIONS OF SCREEN
	LD	A,D
	AND	3	; OFFSET INSIDE SECTION
	LD	H,0
	LD	L,A
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL	;	HL=64*HL
	PUSH	HL
	LD	A,E
	LD	DE,2048	; SECTION LENGTH
	LD	HL,0
	AND	3
	JR	Z,ADD_OFFSET
ADD_SECTION:	ADD	HL,DE
		DEC	A
		AND	3
		JR	NZ,ADD_SECTION
ADD_OFFSET:	
	POP	DE
	ADD	HL,DE
	LD	DE,#4008
	ADD	HL,DE	; HL - begin of screen vertical-address for queen's sprite 
	LD	A,C
	SLA	A
	LD	D,0
	LD	E,A
	ADD	HL,DE	; HL - final address = vertiacal-adress + horizontal-adress
	CALL	DRAW_QUEEN
	INC	IX
	INC	C	; increase number of column
	DJNZ	QUEEN
	RET

DRAW_QUEEN:	PUSH	HL
		PUSH	DE
		PUSH	BC
		PUSH	AF	
		LD	DE,HL	; HL - SCREEN ADDR
		LD	HL,QUEEN_SPR
		LD	B,16
NEXT_LINE:	LD	A,(DE)
		XOR	(HL)
		LD	(DE),A	; XOR BYTE OF SPRITE ON SCREEN
		INC	HL
		INC	E
		LD	A,(DE)
		XOR	(HL)
		LD	(DE),A	; XOR NEXT BYTE ON THE SAME LINE OF SPRITE ON SCREEN
		INC	HL	
		DEC	E
		LD	A,D
		AND	7
		CP	A,7
		JR	NZ,DRAW_Q1	; IF IT IS THE SAME CHAR ON SCREEN
		LD	A,D		
		AND	#F8
		LD	D,A
		LD	A,E
		ADD	A,32
		LD	E,A		; IF NOT GO TO NEXT CHAR LINE
		JR	DRAW_Q2
DRAW_Q1:	INC	D	; NEXT LINE ADDR +#FF
DRAW_Q2:
		DJNZ	NEXT_LINE
		POP	AF
		POP	BC
		POP	DE
		POP	HL
		RET

KEYBOARD_READ:
    LD BC, #7FFE  ; Строка Space/SHIFT (бит 0=Space)
    IN A, (C)
    BIT 0, A
    JR NZ, NO_SPACE
    LD A, 1         ; Space нажата
    RET
NO_SPACE:
    LD BC, #FBFE  ; Строка QAZ (Q=бит0, A=бит1)
    IN A, (C)
    BIT 1, A
    JR NZ, NO_Q
    LD A, 2         ; Q нажата
    RET
NO_Q:
    LD	BC, #FDFE
    IN	A, (C)
    BIT 0, A
    JR NZ, NO_A
    LD A, 3         ; A нажата
    RET
NO_A:
    LD BC, #DFFE  ; Строка PO (P=бит2, O=бит3)
    IN A, (C)
    BIT 0, A
    JR NZ, NO_P
    LD A, 4         ; P нажата
    RET
NO_P:
    BIT 1, A
    JR NZ, NO_O
    LD A, 5         ; O нажата
    RET
NO_O:
    LD A, 0         ; Ничего не нажато
    RET

MARKER_COLOR:	DB	%00100001
MARKER_BACK:	DB	0,0,0,0,0,0,0,0	
QUEENS_ROW:	DB	0
QUEENS_COL:	DB	0
QUEENS_POS:	DW	0		; Address from "8queen.bin" has to be copied here
		DB	#15,#86,#37,#24
		DB	#25,#86,#37,#14
		DB	#35,#86,#17,#24
		DB	#45,#86,#37,#21
		DB	#51,#86,#37,#24
		DB	#65,#81,#37,#24
		DB	#75,#86,#31,#24
		DB	#85,#16,#37,#24

SAVE_SP:	DW	0
QUEEN_SPR1:	DB $00, $00, $03, $c0, $0f, $f0, $1f, $f8
  		DB $3f, $fc, $3f, $fc, $7f, $fe, $7f, $fe
		DB $7f, $fe, $7f, $fe, $3f, $fc, $3f, $fc
		DB $1f, $f8, $0f, $f0, $03, $c0, $00, $00
QUEEN_SPR2:	DW $ffff, $ffff, $ffff, $ffff
		DW $ffff, $ffff, $ffff, $ffff
		DW $ffff, $ffff, $ffff, $ffff
		DW $ffff, $ffff, $ffff, $ffff
QUEEN_SPR:	DW $0000, $fe7f, $fe7f, $fe7f
		DW $fe7f, $fe7f, $fe7f, $fe7f
		DW $fe7f, $fe7f, $fe7f, $fe7f
		DW $fe7f, $fe7f, $fe7f, $0000

	ORG	 $8600
CALC_AND_DRAW:	incbin	"8queen.bin"

	SAVEBIN "chessboard.bin",START,$-START
	SAVESNA "chessboard.sna", START
